# Generated by Django 2.2.6 on 2019-10-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettype',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
