# Generated by Django 2.2.6 on 2019-10-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20191023_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet'),
        ),
    ]
